### ISSUE TITLE
WEB_CONCURRENCY env var is overwritten

### ISSUE THREAD

**Issue by ipmb** [heroku/buildpacks-nodejs#210]
I'm deploying an image built using this buildpack to AWS ECS (Fargate). The task definition sets the environment variable `WEB_CONCURRENCY=1`.

## Expected Result

`WEB_CONCURRENCY` will remain at the manually defined `1`

## Actual Result

`WEB_CONCURRENCY` is set to `28`

## Additional info

I'm using the following buildpacks:

```toml
[[buildpacks]]
  api = "0.6"
  homepage = "https://github.com/heroku/buildpacks-nodejs"
  id = "heroku/nodejs-engine"
  version = "0.8.0"

[[buildpacks]]
  api = "0.6"
  homepage = "https://github.com/heroku/buildpacks-nodejs"
  id = "heroku/nodejs-npm"
  version = "0.5.0"

[[buildpacks]]
  api = "0.2"
  id = "heroku/procfile"
  version = "0.6.2"

[[buildpacks]]
  api = "0.4"
  id = "heroku/python"
  version = "0.3.1"
```

This behavior is not present in `nodejs-engine@0.7.5`.
